package com.thery.paymybuddy.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents the relationship between two clients who are friends.
 * This entity maps to the "userconnections" table in the database.
 */
@Setter
@Getter
@Entity
@Table(name = "clientrelationships")
@IdClass(ClientRelationshipsPrimaryKeyComposite.class)
public class ClientRelationships {

    /**
     * The primary key representing the user in the friendship.
     */
    @Id
    @ManyToOne
    @JoinColumn(name = "client_id", nullable = false)
    private Client client;

    /**
     * The primary key representing the friend in the friendship.
     */
    @Id
    @ManyToOne
    @JoinColumn(name = "friend_id", nullable = false)
    private Client friend;

    // Getters and setters are generated by Lombok
}